on: pull_request
jobs:
  deploy_build_dev:
    name: Build and push dev container
    env:
      AZURE_CONTAINER_REGISTRY_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY_SERVER }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master
        with: 
          fetch-depth: '0'
      
      - name: 'Get PR Number'
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{github.token}}
          script: |
            const core = require('@actions/core')
            const prNumber = context.payload.number;
            core.exportVariable('PULL_NUMBER', prNumber);

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY_SERVER }}
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t base --build-arg GITHUB_SHA_ARG=${{ github.sha }} --build-arg TAG_VERSION=dev-$PULL_NUMBER .

      - name: Tag :steps.tag.output.new_tag
        run: docker tag base $AZURE_CONTAINER_REGISTRY_SERVER/cv-19-benefit:dev-$PULL_NUMBER

      - name: Push container to Azure Container Registry
        run: docker push $AZURE_CONTAINER_REGISTRY_SERVER/cv-19-benefit

      - uses: azure/webapps-container-deploy@v1
        with:
          app-name: 'EsPbDtsCb19AppService'
          slot-name: 'dev'
          images: '${{ secrets.AZURE_CONTAINER_REGISTRY_SERVER }}/cv-19-benefit:dev-$PULL_NUMBER'

      - name: Azure logout
        run: |
          az logout
