  
on:
  push:
    branches:
      - master
jobs:
  deploy_build_dev:
    name: Build and push dev container
    env:
      AZURE_CONTAINER_REGISTRY_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY_SERVER }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master
        with: 
          fetch-depth: '0'

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY_SERVER }}
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t base --build-arg GITHUB_SHA_ARG=${{ github.sha }} --build-arg TAG_VERSION=dev-${{ github.sha }} .

      - name: Tag :steps.tag.output.new_tag
        run: docker tag base $AZURE_CONTAINER_REGISTRY_SERVER/cv-19-benefit:dev-${{ github.sha }}

      - name: Push container to Azure Container Registry
        run: docker push $AZURE_CONTAINER_REGISTRY_SERVER/cv-19-benefit:dev-${{ github.sha }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'EsPbDtsCb19AppService'
          slot-name: 'dev'
          images: '${{ secrets.AZURE_CONTAINER_REGISTRY_SERVER }}/cv-19-benefit:dev-${{ github.sha }}'

      - name: Azure logout
        run: |
          az logout
